### ISSUE TITLE
some more requests

### ISSUE THREAD

**Issue by greyltc** [uio-ess/data-coolection#2]
1. Please add an attribute to both the spectrometer group and the camera group called
`Capture Time`. this will now match the field in the wavefront group and it will be a generic field that specifies how long the data was collected for
1. please change the `wavefront` group name to `oscope`

**Comment by hgjersdal** [comment]
Done and done. In experimental branch.

**Comment by greyltc** [comment]
Oh no. I'm expecting capture time to be the length of time the data was collected for. Just for field name consistency for deciding how long to integrate the current waveform for. Instant measurements like a temperature measurement should have 0 for a capture time.

**Comment by hgjersdal** [comment]
Ah, that makes more sense :) Capture Time is now a duration, the other thing is back to being called timestamp. All devices now have a 'Capture Time', the corresponding attribute with a pv-name has been removed from the spectrometer and camera.
